### ISSUE TITLE
Script don't work since yesterday - or server problems?

### ISSUE THREAD

**Issue by slydlake** [ttimpe/homebridge-midea#3]
First of all: Thank you very very much!
I tried since two month to get it run with HomeKit and open hab. But I have always the problem that the target temperature set only to 17°.

But with your script, everything works fine and ultra fast! The target temperature is also working!

Since yesterday it is not working anymore.
Maybe there is a problem with the Midea servers? Because I have a problem with the Midea app too. Maybe there is a change in the API?

Do you have also problems?
Here is my log:

```
[2020-6-18 17:00:14] [Klimaanlage] "failed\tto connect:connection timed out\n"
[2020-6-18 17:00:14] [Klimaanlage] send successful
[2020-6-18 17:00:14] [Klimaanlage] TypeError: Cannot read property 'reply' of undefined
    at Request._callback (/usr/lib/node_modules/homebridge-midea/index.js:479:95)
    at Request.self.callback (/usr/lib/node_modules/homebridge-midea/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-midea/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (/usr/lib/node_modules/homebridge-midea/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2020-6-18 17:00:14] [Klimaanlage] TypeError: Cannot read property 'reply' of undefined
    at Request._callback (/usr/lib/node_modules/homebridge-midea/index.js:479:95)
    at Request.self.callback (/usr/lib/node_modules/homebridge-midea/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-midea/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (/usr/lib/node_modules/homebridge-midea/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2020-6-18 17:00:14] [Klimaanlage] undefined
[2020-6-18 17:00:14] [Klimaanlage] Try to relogin
[2020-6-18 17:00:14] [Klimaanlage] {"msg":"OK","result":{"loginId":"24c2a9b3-19e1-4706-b027-08407ac33764"},"errorCode":"0"}
[2020-6-18 17:00:15] [Klimaanlage] {"msg":"OK","result":{"originPrivateVersion":"","nickname":"MAILADRESS_I_CUT_OUT","sessionId":"d257fa7e83234c2f8b59e2d45ccd381820200618150014260","accessToken":"ccf0e7ccc87d0b2899aec5d51e2a63a6d0a56da5a07373989bf6c3af1b7ca893","userId":"2618325","versionCode":"","leftCount":""},"errorCode":"0"}
[2020-6-18 17:00:15] [Klimaanlage] Login successful
[2020-6-18 17:00:22] [Klimaanlage] "failed\tto connect:connection timed out\n"
[2020-6-18 17:00:22] [Klimaanlage] send successful
[2020-6-18 17:00:22] [Klimaanlage] TypeError: Cannot read property 'reply' of undefined
    at Request._callback (/usr/lib/node_modules/homebridge-midea/index.js:479:95)
    at Request.self.callback (/usr/lib/node_modules/homebridge-midea/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-midea/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (/usr/lib/node_modules/homebridge-midea/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2020-6-18 17:00:22] [Klimaanlage] TypeError: Cannot read property 'reply' of undefined
    at Request._callback (/usr/lib/node_modules/homebridge-midea/index.js:479:95)
    at Request.self.callback (/usr/lib/node_modules/homebridge-midea/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-midea/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (/usr/lib/node_modules/homebridge-midea/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2020-6-18 17:00:22] [Klimaanlage] update Command still failed after relogin
```

**Comment by ttimpe** [comment]
Funnily enough it seems to work again. As suggested in #4, I would love to make this a local plugin if possible and will investigate how to do that. If anyone wants to help, go ahead.

**Comment by slydlake** [comment]
Yeah. Now it seems to work for me again. So just temporary server problems...

This would be great, but for me the local solution is not working. Seems that it depends on the ac models. So for that I cannot help.

But I will try to add the swing mode and fan speed option in your solution. I will take a look in the next days for that 😉 
So I think we can close this 😊
