### ISSUE TITLE
Login / Communication Error

### ISSUE THREAD

**Issue by tso33** [ttimpe/homebridge-midea#4]
Hello and thank you very much. I never managed to make this work. I am getting a lot of login error and after succesful login i have communication error with AC. I tryied a lot of plugins on other platforms with server connection and always somethings getting wrong with midea servers. the only pluggin that works perfectly is the local homeassistant plugin from Mac_Zhou. Why you dont try to make this local? I think is more stable.

Here is the log:

[6/19/2020, 11:06:31 AM] [CH] {"msg":"OK","result":{"reply":"7ff5a21feb114399c27810b13eca2d44d3a15f25d19b9cf35bcd7a4e4ea7549e7b624232465598257a9723ea5034a597ca59ad1867256337b4427391ff65ea1618ade5eea4924817c9e303de53480b9692af2b44dc83474d238e09e83edbcf28ab85b2cc30143d357f64f598d2cb41edfea1e814d4ff71953b1e3336f2502ada50a8765975aa4c3af8402f78bc2f57dc0311262cf360759904b1ce1297591cf23561593b4417ff3f6b74f72675b857053736adf788f42b3efbdd26ac2d384c367b624232465598257a9723ea5034a5970b6fba17b80c7d636eaaf6cac3e46ee8"},"errorCode":"0"}
[6/19/2020, 11:06:31 AM] [CH] send successful
[6/19/2020, 11:06:31 AM] [CH] target temperature 23
[6/19/2020, 11:06:31 AM] [CH] powerState is set to false
[6/19/2020, 11:06:31 AM] [CH] operational mode is set to 3
[6/19/2020, 11:06:31 AM] [CH] Update successful
[6/19/2020, 11:06:33 AM] [CH] "failed\tto connect:connection timed out\n"
[6/19/2020, 11:06:33 AM] [CH] send successful
[6/19/2020, 11:06:33 AM] [CH] failed    to connect:connection timed out

[6/19/2020, 11:06:33 AM] [CH] TypeError: Cannot read property 'reply' of undefined
    at Request._callback (/homebridge/node_modules/homebridge-midea/index.js:479:95)
    at Request.self.callback (/homebridge/node_modules/homebridge-midea/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-midea/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Gunzip.<anonymous> (/homebridge/node_modules/homebridge-midea/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at Gunzip.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[6/19/2020, 11:06:33 AM] [CH] TypeError: Cannot read property 'reply' of undefined
    at Request._callback (/homebridge/node_modules/homebridge-midea/index.js:479:95)
    at Request.self.callback (/homebridge/node_modules/homebridge-midea/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-midea/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Gunzip.<anonymous> (/homebridge/node_modules/homebridge-midea/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at Gunzip.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[6/19/2020, 11:06:33 AM] [CH] undefined
[6/19/2020, 11:06:33 AM] [CH] Try to relogin
[6/19/2020, 11:06:38 AM] [CH] {"msg":"OK","result":{"loginId":"fe75f980-b875-4f89-a19e-fd778213fb1c"},"errorCode":"0"}
[6/19/2020, 11:06:44 AM] [CH] {"msg":"OK","result":{"originPrivateVersion":"","nickname":"tso.tvbox@gmail.com","sessionId":"4393d5aa0ab640308b5c0d16d937012f20200619080643569","accessToken":"9cbc17af4c9054a22c9098b9d60889f8d0a56da5a07373989bf6c3af1b7ca893","userId":"2561735","versionCode":"","leftCount":""},"errorCode":"0"}
[6/19/2020, 11:06:44 AM] [CH] Login successful
[6/19/2020, 11:06:51 AM] [CH] {"msg":"OK","result":{"reply":"73bca300ba10d1b80b029720da03710d28d0cf762c78999f30fd9935a25dec852c59af17e993f660f4fb5af013a403fe6b2b432e93a979614f3fcaa76bc7cfc298d66da47dfaffff66e70c37dd06366ab1c05eb167630087f62ed6806d99c638d239aa016c60ae31e0301bd4e1664ede9297ed89b6e30c802d5fe4725238d2772bdd82b8466738bd8e59c3590827c5ec29902ed2d3c73a1fa29c8676cd85213deb4c3da5b99747958a570040edafdc181367e3778b392149886e89b5c680b20a98d66da47dfaffff66e70c37dd06366a7d7cf8b0cf7c45a7d6485b22d7faf8c0"},"errorCode":"0"}
[6/19/2020, 11:06:51 AM] [CH] send successful
[6/19/2020, 11:06:51 AM] [CH] target temperature 25
[6/19/2020, 11:06:51 AM] [CH] powerState is set to false
[6/19/2020, 11:06:51 AM] [CH] operational mode is set to 2
[6/19/2020, 11:06:58 AM] [CH] Triggered SET TargetHeatingCoolingState: 0
[6/19/2020, 11:06:58 AM] [CH] Command: {"data":[170,30,172,0,0,0,0,0,3,2,64,66,89,102,127,127,0,48,0,0,0,0,0,0,0,0,0,0,0,135]}
[6/19/2020, 11:06:58 AM] [CH] Command + Header: [90,90,1,16,90,0,32,0,1,0,0,0,189,179,57,14,12,5,20,20,29,129,0,0,0,16,0,0,0,4,2,0,0,1,0,0,0,0,0,0,170,30,172,0,0,0,0,0,3,2,64,66,89,102,127,127,0,48,0,0,0,0,0,0,0,0,0,0,0,135,59,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
[6/19/2020, 11:07:01 AM] [CH] Triggered SET TargetHeatingCoolingState: 2
[6/19/2020, 11:07:01 AM] [CH] Command: {"data":[170,30,172,0,0,0,0,0,3,2,64,67,89,102,127,127,0,48,0,0,0,0,0,0,0,0,0,0,0,135]}
[6/19/2020, 11:07:01 AM] [CH] Command + Header: [90,90,1,16,90,0,32,0,1,0,0,0,189,179,57,14,12,5,20,20,29,129,0,0,0,16,0,0,0,4,2,0,0,1,0,0,0,0,0,0,170,30,172,0,0,0,0,0,3,2,64,67,89,102,127,127,0,48,0,0,0,0,0,0,0,0,0,0,0,135,58,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
[6/19/2020, 11:07:10 AM] [CH] "failed\tto connect:connection timed out\n"
[6/19/2020, 11:07:10 AM] [CH] send successful
[6/19/2020, 11:07:10 AM] [CH] failed    to connect:connection timed out

[6/19/2020, 11:07:10 AM] [CH] TypeError: Cannot read property 'reply' of undefined
    at Request._callback (/homebridge/node_modules/homebridge-midea/index.js:479:95)
    at Request.self.callback (/homebridge/node_modules/homebridge-midea/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-midea/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Gunzip.<anonymous> (/homebridge/node_modules/homebridge-midea/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at Gunzip.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[6/19/2020, 11:07:10 AM] [CH] TypeError: Cannot read property 'reply' of undefined
    at Request._callback (/homebridge/node_modules/homebridge-midea/index.js:479:95)
    at Request.self.callback (/homebridge/node_modules/homebridge-midea/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-midea/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Gunzip.<anonymous> (/homebridge/node_modules/homebridge-midea/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at Gunzip.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[6/19/2020, 11:07:10 AM] [CH] undefined
[6/19/2020, 11:07:10 AM] [CH] Try to relogin
[6/19/2020, 11:07:15 AM] [CH] {"msg":"OK","result":{"loginId":"111530ae-5a16-45f5-b339-de585da84ec1"},"errorCode":"0"}
[6/19/2020, 11:07:16 AM] [CH] {"msg":"ASYN-Antwort existiert nicht","errorCode":"3176"}
[6/19/2020, 11:07:16 AM] [CH] Command was not accepted by device. Command wrong or device not reachable 17592186080559 ASYN-Antwort existiert nicht
[6/19/2020, 11:07:22 AM] [CH] {"msg":"OK","result":{"originPrivateVersion":"","nickname":"tso.tvbox@gmail.com","sessionId":"cd0fffc1f7e8400c85a6e54585c8f52820200619080721195","accessToken":"0ae99c2d99693a16579f7faba7e8914bd0a56da5a07373989bf6c3af1b7ca893","userId":"2561735","versionCode":"","leftCount":""},"errorCode":"0"}
[6/19/2020, 11:07:22 AM] [CH] Login successful
[6/19/2020, 11:07:26 AM] [CH] {"msg":"Sitzung ungültig","errorCode":"3106"}
[6/19/2020, 11:07:26 AM] [CH] Sending failed device returns an error
[6/19/2020, 11:07:26 AM] [CH] 3106
[6/19/2020, 11:07:26 AM] [CH] Sitzung ungültig
[6/19/2020, 11:07:26 AM] [CH] Sitzung ungültig
[6/19/2020, 11:07:26 AM] [CH] Try to relogin
[6/19/2020, 11:07:26 AM] [CH] {"msg":"Sitzung ungültig","errorCode":"3106"}
[6/19/2020, 11:07:26 AM] [CH] Sending failed device returns an error
[6/19/2020, 11:07:26 AM] [CH] 3106
[6/19/2020, 11:07:26 AM] [CH] Sitzung ungültig
[6/19/2020, 11:07:26 AM] [CH] Sitzung ungültig
[6/19/2020, 11:07:26 AM] [CH] Try to relogin
[6/19/2020, 11:07:31 AM] [CH] {"msg":"Sitzung ungültig","errorCode":"3106"}
[6/19/2020, 11:07:31 AM] [CH] Sending failed device returns an error
[6/19/2020, 11:07:31 AM] [CH] 3106
[6/19/2020, 11:07:31 AM] [CH] Sitzung ungültig
[6/19/2020, 11:07:31 AM] [CH] Sitzung ungültig
[6/19/2020, 11:07:31 AM] [CH] Try to relogin
[6/19/2020, 11:07:31 AM] [CH] Failed to send command
[6/19/2020, 11:07:31 AM] [CH] "<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>openresty</center>\r\n</body>\r\n</html>\r\n"
[6/19/2020, 11:07:31 AM] [CH] 500
[6/19/2020, 11:07:31 AM] [CH] Command still failed after relogin
[6/19/2020, 11:07:36 AM] [CH] {"msg":"OK","result":{"loginId":"1b6c2f0f-3392-4cc8-be62-d3b4f7f699cb"},"errorCode":"0"}
[6/19/2020, 11:07:36 AM] [CH] {"msg":"OK","result":{"loginId":"e0d36f30-f450-4da8-ac24-45322c4a6d18"},"errorCode":"0"}
[6/19/2020, 11:07:41 AM] [CH] {"msg":"OK","result":{"loginId":"81869f72-8e86-4247-a5a6-434498c2c3f2"},"errorCode":"0"}
[6/19/2020, 11:07:41 AM] [CH] {"msg":"Passwort falsch, bitte erneut eingeben","errorCode":"3101"}
[6/19/2020, 11:07:41 AM] [CH] Passwort falsch, bitte erneut eingeben
[6/19/2020, 11:07:41 AM] [CH] 3101
[6/19/2020, 11:07:41 AM] [CH] Login failed

**Comment by ttimpe** [comment]
This is the same issue as #3.

**Comment by ttimpe** [comment]
Funnily enough it seems to work again. As suggested in #4, I would love to make this a local plugin if possible and will investigate how to do that. If anyone wants to help, go ahead.
