### ISSUE TITLE
Can't switch mode on AC(EU-OSK103 dongle)

### ISSUE THREAD

**Issue by barbariska108** [ttimpe/homebridge-midea#48]
When I start an AC and switching the state to "Cool" -- in the Home app I see needed temp and state. 
However, in the Midea Air app temp is 20 C(on the Home app I set it to 23C) and AC mode is "Fan".

Host: `macOS 11.5.1`
Version: `homebridge-midea v1.5.5`
Node version: `v12.22.1`
NPM cersion: `v7.20.3`
HB version: `v4.41.2`

Logs: 

`[8/1/2021, 4:20:03 PM] [homebridge-midea] Triggered GET Active, returning 1
[8/1/2021, 4:20:03 PM] [homebridge-midea] Triggered GET CurrentHeaterCoolerState
[8/1/2021, 4:20:03 PM] [homebridge-midea] Triggered GET TargetHeaterCoolerState while powerState is 1
[8/1/2021, 4:20:03 PM] [homebridge-midea] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[8/1/2021, 4:20:03 PM] [homebridge-midea] Error: 
    at TargetHeaterCoolerState.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at TargetHeaterCoolerState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at MideaAccessory.handleTargetHeaterCoolerStateGet (/usr/local/lib/node_modules/homebridge-midea/lib/MideaAccessory.js:232:9)
    at TargetHeaterCoolerState.emit (events.js:314:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at TargetHeaterCoolerState.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)`

Config: 

`        {
            "user": "Midea acc mail",
            "password": "PWD",
            "interval": 1,
            "devices": [
                {
                    "deviceId": "Living Room",
                    "supportedSwingModes": "Both"
                }
            ],
            "platform": "midea",
            "_bridge": {
                "username": "AC local MAC",
                "port": Local Port
            }`

**Comment by barbariska108** [comment]
UPD: I was added a `  "temperatureSteps": 1,
                    "fanOnlyMode": false` in the config, now I can fully control a temperature, but can't switch mode(ex. from Cool to Warn and so on)
